//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.14 at 01:35:12 PM CEST 
//


package eu.allowensembles.presentation.main.map;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.allowensembles.presentation.main.map package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.allowensembles.presentation.main.map
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Routes }
     * 
     */
    public Routes createRoutes() {
        return new Routes();
    }

    /**
     * Create an instance of {@link Routes.Route }
     * 
     */
    public Routes.Route createRoutesRoute() {
        return new Routes.Route();
    }

    /**
     * Create an instance of {@link Routes.Route.Leg }
     * 
     */
    public Routes.Route.Leg createRoutesRouteLeg() {
        return new Routes.Route.Leg();
    }

    /**
     * Create an instance of {@link Routes.Route.Leg.PrivacyParameters }
     * 
     */
    public Routes.Route.Leg.PrivacyParameters createRoutesRouteLegPrivacyParameters() {
        return new Routes.Route.Leg.PrivacyParameters();
    }

    /**
     * Create an instance of {@link Routes.Route.Leg.TransportType }
     * 
     */
    public Routes.Route.Leg.TransportType createRoutesRouteLegTransportType() {
        return new Routes.Route.Leg.TransportType();
    }

    /**
     * Create an instance of {@link Routes.Route.Leg.SafetyParameters }
     * 
     */
    public Routes.Route.Leg.SafetyParameters createRoutesRouteLegSafetyParameters() {
        return new Routes.Route.Leg.SafetyParameters();
    }

    /**
     * Create an instance of {@link Routes.Route.Leg.PrivacyParameters.DataRequestMask }
     * 
     */
    public Routes.Route.Leg.PrivacyParameters.DataRequestMask createRoutesRouteLegPrivacyParametersDataRequestMask() {
        return new Routes.Route.Leg.PrivacyParameters.DataRequestMask();
    }

}
